### ISSUE TITLE
Sitemap regeneration period

### ISSUE THREAD

**Issue by leonidasfs** [Hostwiki/wikijs-sitemap#2]
hourly sitemap regeneration is a bit overkill, why not set it to weekly by default? Keep in mind that Google is periodically crawling the sitemap!

**Comment by Philipinho** [comment]
I changed it to every 24 hours in https://github.com/Hostwiki/wikijs-sitemap/commit/43ea51ee7f565e297cae21de2bb299981c53576c.
It could be configurable via environment variables in the future.
