### ISSUE TITLE
Sitemap mysql undefined domain

### ISSUE THREAD

**Issue by sspavlenko** [Hostwiki/wikijs-sitemap#7]
**Hi!**
Thanks for implementing the sitemap for mysql.
I have a problem below in the screenshot.
![image](https://user-images.githubusercontent.com/97730182/230460510-6e065fda-d121-474b-9ed9-0759d2d270b4.png)

Wikijs in a container according to the examples. Tried to proxy through nginx and haproxy.
Could you suggest what is the problem. 
Why is the domain not visible (undefined)?
 Maybe I forgot to specify it somewhere?

**Comment by Philipinho** [comment]
Is the “Site URL” set in your Wikijs dashboard? That is what it uses.

**Comment by sspavlenko** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/97730182/230476053-ac6166c9-685a-45af-8bf1-0011a4a43337.png)
But I planned to use several languages ua and ru.
Now only ru and default url https://wiki.mydomain.pp.ua/ru/home but even with this language, the problem does not go away.
![image](https://user-images.githubusercontent.com/97730182/230477914-b3affff5-56f9-4874-956f-1405b5b6e45b.png)
I also tried to change the domain in the control panel to https://wiki.mydomain.pp.ua/ru/home this also didn't work(((

**Comment by sspavlenko** [comment]
If I disabled multilanguages in control panel it doesn't help either.

**Comment by Philipinho** [comment]
I will have a look on the code.

**Comment by Philipinho** [comment]
I tried it on MYSQL 8 and couldn't reproduce the bug.  
Can you let me know your MYSQL version? Are you running it on docker?

**Comment by sspavlenko** [comment]
Yes I am running in docker. 
I am using mariadb version 10.5.19

**Comment by Philipinho** [comment]
I will try it on MariaDB and give feedback.

**Comment by Philipinho** [comment]
I can reproduce the bug with Mariadb. I will work on a fix.

**Comment by Philipinho** [comment]
The new pull request fixes this issue.
Change your DB_TYPE to `DB_TYPE=mariadb`.

**Comment by sspavlenko** [comment]
Thanks it's worked
